name: Workflows Build Application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Go 1.14.3
        uses: actions/setup-go@v2
        with:
          go-version: 1.14.3
        id: go

      - name: Perform Unit Testing
        run: go test passage/handler/passage_test.go -v

      - name: Build main application
        run: go build .
